# Generated by Django 4.1.7 on 2024-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("description", models.TextField(max_length=200)),
                ("completed", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
